In [9]:
import numpy as np

def lu_decomposition(A):
    n = len(A)
    L = np.eye(n)  # Initialize L as an identity matrix
    U = np.array(A, dtype=float)  # Copy of A to avoid
    factor = 0
    # modifying the original matrix
    
    for i in range(n):
        # Eliminate elements below the pivot (U[i, i])
        for j in range(i+1, n):
            if U[i, i] == 0:
                raise ValueError("Zero pivot encountered. LU decomposition cannot proceed.")
                factor = U[j, i] / U[i, i]  # Multiplier for row
     # operation
            L[j, i] = factor  # Store multiplier in L
            
            # Update the rows of U
            for k in range(i, n):
                U[j, k] -= factor * U[i, k]
    
    return L, U

In [10]:
# Example usage
A = np.array([[2, 3, 1],
              [4, 7, -1],
              [-2, 1, 2]])

L, U = lu_decomposition(A)

print("Matrix A:\n", A)
print("Lower Triangular Matrix L:\n", L)
print("Upper Triangular Matrix U:\n", U)

Matrix A:
 [[ 2  3  1]
 [ 4  7 -1]
 [-2  1  2]]
Lower Triangular Matrix L:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
Upper Triangular Matrix U:
 [[ 2.  3.  1.]
 [ 4.  7. -1.]
 [-2.  1.  2.]]
