In [3]:
import numpy as np

def is_diagonally_dominant(matrix):
    matrix = np.array(matrix)
    for i in range(len(matrix)):
        diagonal = abs(matrix[i][i])
        row_sum = sum(abs(matrix[i][j]) for j in range(len(matrix)) if j != i)
        if diagonal < row_sum:
            return False
    return True


def display_matrix(matrix):
    matrix = np.array(matrix)
    print("\nMatrix:")
    for row in matrix:
        print(" ", row)
    print(f"\nIs the matrix diagonally dominant? {is_diagonally_dominant(matrix)}\n")


In [5]:
# Not diagonally dominant matrix
matrix1 = [
    [1,  2,  3],
    [4,  5,  6],
    [7,  8,  9]
]

# Diagonally dominant matrix
matrix2 = [
    [4, 1,  0],
    [-1, 4, 1],
    [0, -1,  4]
]

# Strictly diagonally dominant
matrix3 = [
    [10,  1, -2],
    [ 3,  9,  1],
    [ 2, -1,  7]
]

for matrix in [matrix1, matrix2, matrix3]:
    display_matrix(matrix)


Matrix:
  [1 2 3]
  [4 5 6]
  [7 8 9]

Is the matrix diagonally dominant? False


Matrix:
  [4 1 0]
  [-1  4  1]
  [ 0 -1  4]

Is the matrix diagonally dominant? True


Matrix:
  [10  1 -2]
  [3 9 1]
  [ 2 -1  7]

Is the matrix diagonally dominant? True

